### ISSUE TITLE
Kext won't load on boot always

### ISSUE THREAD

**Issue by reelgirly** [vit9696/AppleALC#103]
hey :D

First of all thx for this great KEXT :) 

But got a problem with self built kext as it wont load always the audio devices on boot :/
Mostly they're back after second boot.

Seems to be random :/

OSX 10.10.5.
Device is ALC233 with custom pinconfig and pathmaps.
IGPU is HD4400 with custom framebuffer patches for HDMI audio.

Logs are attached :D

[alc233_not_working.txt](https://github.com/vit9696/AppleALC/files/619402/alc233_not_working.txt)
[alc233_working.txt](https://github.com/vit9696/AppleALC/files/619403/alc233_working.txt)

Any help would be great, thx :)

**Comment by vit9696** [comment]
Hi,

Both logs seem to have exactly the same patching sequence, and the only difference I noticed is that AppleHDA does not request any resources in "not working" case.

The above basically means the issue is not in AppleALC but probably the codec is not initialised properly. My first guess will be to try enabling ResetHDA in clover if you use this bootloader. If it does not help, maybe you could give CodecCommander a try.

Unfortunately I am not an expert in such problems, and they also do not have anything to do with AppleALC development. Such generic AppleHDA patching issues should probably be explored according to the manuals and discussed with people writing the mods.

**Comment by modaifallah** [comment]
same here with intel 530 HD. I always found it will always fail in the first boot after using Windows.
