### ISSUE TITLE
ALC256 partition corruption

### ISSUE THREAD

**Issue by nos1609** [vit9696/AppleALC#110]
Got corrupted partition after first reboot of my freshly installed macOS. Error 8 while checking partition with diskutility and have to reinstall the whole system after. 
Don't know why it cause some interference with my NVMe ssd. Also I'm getting high CPU load using the kext during the first boot.

However no such problems using CloverHDA. And it's a little bit strange since as far as I can see you're sharing the same sources. 

I want leave my system partition intact, so let get things fixed together. I can perform several reinstall to help debugging and fixing. How can I help you with it and what should I provide you?

**Comment by vit9696** [comment]
Hi,
The issues you describe are quite weird. And I am a bit at a loss what to think of.

I do not think AppleALC could really cause any filesystem corruption, since it only performs read operations, and this should be safe. NVMe SSD could be related but I am afraid I do not know anything to suggest in this direction.

As for high CPU load, could you clarify which process actually causes it? Is it kernel_task? Does the issue persist after a reboot? After all we know that Spotlight takes quite some time to index everything right after the installation, and this produces pretty high CPU load.

Also note that AppleALC does hardly anything after AppleHDA is loaded. So if you see kernel_task occupying loads of your CPU time after you booted, it is likely AppleHDA itself. 

We did get reports of similar issues with different resources, and I would suggest starting with decompressing the resources and comparing them to the ones that work fine for you. AppleALC uses optimised packages, so as a result there could be differences and these differences may theoretically cause high CPU load.

**Comment by nos1609** [comment]
@vit9696 could it be due to the AppleHDA patching made by the kext and not by clover itself? CloverHDA also uses five patches and uses same zlibs made by @insanelydeepak . However the AppleHDA patches remain in the config.plist and proceeded by clover. Is there a way to make AppleHDA patches external for your kext the same way? I mean making it the way so the zlibs could be injected by the kext and AppleHDA loaded, while patching made on the clover side.

**Comment by vit9696** [comment]
@nos1609 could you please answer the questions in the previous? I am not even sure when exactly you have high CPU load, and what causes it, "during first boot" is not clear at all.

Having patches present in Clover's config.plist will cause issues, you should not do that. This is because AppleALC will have to fully rescan the kext binary instead of finding and replacing a few bytes in the beginning. To remove patches from AppleALC you could edit codec plist and recompile, but it is very unlikely that something like that is related.

I would not be so sure that the zlibs are exactly the same even if the source is mentioned. Please follow what I told you and compare the contents of the files. We have [source releases](https://github.com/vit9696/AppleALC/releases).

**Comment by nos1609** [comment]
@vit9696 yep, sorry about that, I'm aware of sierra's spotlight first boot high load due to siri's requirements, but the kernel task cpu load remains high after spotlight process got finished. Also sometimes I get some kind of distortion after 5-10 minutes of video preview. I'm currently using [this kext](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/2#issuecomment-255294700) to get output working. They are some issues with the jack, but speakers and internal mic are working fine.

**Comment by nos1609** [comment]
@vit9696 maybe trying the DEBUG version might help to find out the root cause of the issue?

**Comment by vit9696** [comment]
So, if you have kernel_task eating CPU resources after system is loaded, it is definitely not AppleALC, but AppleHDA. Since it is AppleHDA, the issue is in the resources, and obviously changing anything in AppleALC code or enabling its debug mode will simply not help.

Since the resources were provided by @insanelydeepak, I think you might want to talk to him, and not to us. Plus I repeat… there might be certain substantial differences between what we have in AppleALC, and what exists in cloverHDA. Please check that _first of all_.

**Comment by dodvip123** [comment]
i had this too on my Dell 7559 when I installed the kext to /Library/Extensions. Now I have it on EFI/Clover/kexts/other/ which works but sometimes it does not load (reboot fixes it). I have one question though, is it possible to add HDMI audio out support for mobile HD530 (0x191b0000)?

**Comment by nos1609** [comment]
@vit9696 Finally checked everything and hopefully fixed the issue. For now. It's not finished as they're bug in the layout itself, but at least I've fixed the 1500% load caused by kerneltask and the partition deterioration during sleep. As I do not know how to creat these zlib files from scratch I've simly replaced them from scratch I had simply to replace the layout13.xml.zlib & PlatformsID.xml.zlib with the versions from a working kext provided in the open issue by @insanelydeepak. Audiojack is not yet fixed, but at least we now the cause of the issue for now.

I'm not a git' specialist, so I'll simply leave you the needed files to correct the error just right here in attach. 
[Архив.zip](https://github.com/vit9696/AppleALC/files/706383/default.zip)

I'm gonna try to find some working layout files during the week, so please keep the issue open till that moment.

And no, that was not caused by NVMe patches😉
To find out that I've tested using both the 2 known approaches to bring up the ssd, and both showed the same final 🚫 at loading the system after few reboots.

Hope we might fix this soon, now aware of the culprit in this issue.

**Comment by vit9696** [comment]
@nos1609 that's interesting. In theory the resources we use should be not different from the original ones.
@vandroiy2013 could you check what's wrong with what we have? These freezes are not too funny. Might those be the optimisations?

**Comment by vandroiy2013** [comment]
I'll contact @insanelydeepak for the clarification. In my opinion existing resources in AppleALC was a kind of test version. Too many changes in it...
Left - existing resources, Right - new resources provided by @nos1609 
![2017-01-15 18 55 51](https://cloud.githubusercontent.com/assets/8144780/21964456/f48e90ce-db54-11e6-8a1d-a18d5eb8aa37.png)

**Comment by insanelydeepak** [comment]
Hi 
Interesting I did too many fixes to ALC256 to work with many systems  , I don't remember for which system **Left** Side resource were made **Right** I assumes this is perfect for your system and if other don't issue can for them too in my repo too 

BTW good catchUp @nos1609 
issue should be closed

**Comment by nos1609** [comment]
@insanelydeepak the only issue is a strange device in the input called "External speakers". However  seems like @syscl had solved this mysterious input...

**Comment by syscl** [comment]
@nos1609 @insanelydeepak But we lost External speaker.

On ALC 298, there's ext mic on both XPS 15 9550 and Surface Pro 4.

syscl

**Comment by insanelydeepak** [comment]
@syscl 

> But we lost External speaker
what ??

> On ALC 298, there's ext mic on both XPS 15 9550 and Surface Pro 4.
 I was unable to detect ext mic on XPS 9550 and it was present in surface pro
