### ISSUE TITLE
FAQ is missing the most important question

### ISSUE THREAD

**Issue by magicgoose** [vit9696/AppleALC#161]
Maybe it's just me being dumb today, but I think this question deserves an answer there (or right in the README):
What's the main point? / Which problem does this project solve?

The description has this:

> An open source kernel extension enabling **native macOS HD audio for not officially supported codecs** without any filesystem modifications.

I think, this needs to be expanded, it's not clear as it is… at least with a link to some place where these things are explained — what's the difference between native/non-native HD audio and why does it matter, what does it mean for a _codec_ to be not officially supported and what kind of support are we talking about. Without context, these words may mean a lot of very different things.

**Comment by vit9696** [comment]
Hi, are you sure you need that information? If you stumbled on this project across the net, you almost certainly don't need it.

If you check the support topics from the readme, you could get the idea. The list of the supported (hardware) codecs is available on the [wiki](https://github.com/vit9696/AppleALC/wiki/Supported-codecs) and the matter of native/non-native audio driver usage is relatively important due to e.g. AppleHDA-specific plugins required for playing DRM-protected movies in iTunes.

However, I have no idea why it bothered you and what could you do with this information :%.
