### ISSUE TITLE
Sound working at random on ALC269 on 10.11.6

### ISSUE THREAD

**Issue by phoe** [vit9696/AppleALC#176]
I have a weird issue - the sound devices only appear randomly, once per about ten reboots of my systems and they work fine until the next reboot. In most cases, the devices do not appear at all.

I have ALC269 with layout 29.
I have AppleALC and Lilu installed.

See the attached logs. They contain a few reboots' worth of data, INCLUDING one where the sound actually DID work. See the timestamps to separate them - pay attention that `Jun 17 00:16:27` and `Jun 17 00:16:34` belong to one run, the one that was successful.

https://pastebin.com/TB5W4kHm

**Comment by vit9696** [comment]
Hi, this is weird to be honest. It feels like AppleHDA is sometimes not getting loaded, but I cannot be sure without additionally seeing the log output from the debug version of Lilu.

I would like to have a couple more logs (working/not working boot). Could you try adding -liludbg in addition to -alcdbg and get the unified boot log (use grep -E 'AppleALC|Lilu' for filtering)? Also, ideally each boot is in a separate file, since there will be quite an amount of lines. In addition to the log please provide kextstat output for each boot. 

And a couple of quick questions:
Do you have any kextpatches in Clover?
Is AppleHDA codesign valid?
Do you use CodedCommander (is it needed for this layout)?
Are Lilu and AppleALC installed on EFI?

**Comment by phoe** [comment]
Hey,

I will be able to test more in two-three days - I will have some free time then and that is when I will collect the logs for you.

As a temporary workaround that might stick forever, I'm using VoodooHDA as it works out of the box for me. But I'll get back to you in order to fix this thing, since it's weird to be honest and best be fixed or at least figured out.

**Comment by vit9696** [comment]
I guess I will close this for now, I made some changes to Lilu that might affect the behaviour, but to be honest, if VoodooHDA works fine for you, there is no real need to bother. We will unlikely figure enough for a stable solution.
