### ISSUE TITLE
Microphone not working with ALC221

### ISSUE THREAD

**Issue by Nitrouze** [vit9696/AppleALC#244]
Hi,
Already posted this issue @ http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/ but haven't got any answer there. 

None of the microphones (rear blue jack or front black jack) seems to be working with ALC221 on HP8300.

I would be grateful if someone could help me to debug.

Thanks in advance for your help.

Edit: attach linux codec dump + ALC221 data sheet 
[ALC221-Realtek Microelectronics.pdf.zip](https://github.com/vit9696/AppleALC/files/1629304/ALC221-Realtek.Microelectronics.pdf.zip)
[ALC221@HP8300SFF.dump.org.txt](https://github.com/vit9696/AppleALC/files/1629306/ALC221.HP8300SFF.dump.org.txt)

**Comment by Goldfish64** [comment]
Just tested a headset on my system and the mic seems to work ok with both the front/back ports. I'm assuming speakers work fine?

**Comment by Nitrouze** [comment]
Thanks for your reply.
Yes, speakers (line out and internal/jack) are working fine.

Did you test voice level (i.e. Siri) with microphones ? cause I got some input on mine (ambient noise) but voice isn't recognized.
Headset I tried is working well on another machine.

**Comment by Nitrouze** [comment]
Also, am I wrong assuming we should have an entry of type "Mic" in the input section (in addition to the type lineIn) in layout11.xml ?

**Comment by Nitrouze** [comment]
Why was it closed without any inputs ?
Mic IS NOT working and I did not get any answers to my previous questions.
I'm ready to provide any further needed information and time for testing but expecting in return, at least, a mimimum of support.

**Comment by vandroiy2013** [comment]
Because it is not support forum! Try to find author of this resources on insanelymac.com and ask him for help!

**Comment by Nitrouze** [comment]
I tried, no answers there, is it a reason to close without any input ?

**Comment by vandroiy2013** [comment]
YES! Try to read this text carefully [https://github.com/vit9696/AppleALC/issues/new](url)

**Comment by Nitrouze** [comment]
Broken link

**Comment by vandroiy2013** [comment]
Please stop and read this carefully. Otherwise your issue will be left **unaswered** and **closed**.

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/) or [AppleLife.ru](https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/). There could also be local communities providing AppleALC support in your native language.

If you have not working sound, and you **cannot** offer new resources that fix the problem for you, you should go to the **support forums**. Here there are no people who create custom audio resources, or who deal with installation issues.

When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 to avoid kext names scrolling over the panic log you should also [patch your kernel](https://applelife.ru/posts/686953)._

In most cases you need to provide the debug log, for that follow the instructions in [English](https://github.com/vit9696/AppleALC/wiki/Installation-and-usage) or [Russian](https://github.com/vit9696/AppleALC/wiki/Установка-и-использование).  
We have a guide on adding a new codec in [English](https://github.com/vit9696/AppleALC/wiki/Adding-codec-support) and [Russian](https://github.com/vit9696/AppleALC/wiki/Добавление-нового-кодека) as well.  
We have answers to most common questions in [English](https://github.com/vit9696/AppleALC/wiki/Frequently-Asked-Questions) and [Russian](https://github.com/vit9696/AppleALC/wiki/Часто-задаваемые-вопросы).

**Comment by Nitrouze** [comment]
What about this "ou want to discuss technical" as ALC221 isn't working ?

**Comment by vandroiy2013** [comment]
This text is present before issue creation but no one, even you don't try to read it.
