### ISSUE TITLE
ALC 256 - ASUS X541UAK

### ISSUE THREAD

**Issue by maxhartung** [vit9696/AppleALC#256]
Hi,

I have a little problem with my sound on the ASUS X541UAK with ALC 256 codec. The thing is that I put layout-id 56 made by someone else and the headphone jack outputs the sound but the internal laptop speakers does not (no sound with laptop speakers but it's working with headphones). The question is: there is any guide what should I patch in the DSDT or add a new layout id in your kext ?

I am somewhat confused because the headphone jack is outputting sound but the laptop speakers doesn't so the kext is working but something else is the problem. 

I will attach a IOREG,config.plist and DSDT maybe there is something wrong on my side.

The layout-id is defined in the DSDT.

[Debug files for Audio.zip](https://github.com/vit9696/AppleALC/files/1800280/Debug.files.for.Audio.zip)

Thanks a lot !

**Comment by vandroiy2013** [comment]
Please stop and read this carefully. Otherwise your issue will be left **unaswered** and **closed**.

Issue tracker is _not_ a support forum, and if you have installation or usage problems, try asking your questions on [InsanelyMac.com](http://www.insanelymac.com/forum/topic/311293-applealc-—-dynamic-applehda-patching/) or [AppleLife.ru](https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/). There could also be local communities providing AppleALC support in your native language.

If you have not working sound, and you **cannot** offer new resources that fix the problem for you, you should go to the **support forums**. Here there are no people who create custom audio resources, or who deal with installation issues.

When to use issue tracker:
* You have new resources or patches to add but cannot make a pull request
* You have kernel panics, crashes, hangs
* You want to discuss technical or legal stuff

_If you have a kernel panic, please ensure that you have a DEBUG version of the extension and you have `-v keepsyms=1 debug=0x100` boot arguments added. On 10.13 to avoid kext names scrolling over the panic log you should also [patch your kernel](https://applelife.ru/posts/686953)._

In most cases you need to provide the debug log, for that follow the instructions in [English](https://github.com/vit9696/AppleALC/wiki/Installation-and-usage) or [Russian](https://github.com/vit9696/AppleALC/wiki/Установка-и-использование).  
We have a guide on adding a new codec in [English](https://github.com/vit9696/AppleALC/wiki/Adding-codec-support) and [Russian](https://github.com/vit9696/AppleALC/wiki/Добавление-нового-кодека) as well.  
We have answers to most common questions in [English](https://github.com/vit9696/AppleALC/wiki/Frequently-Asked-Questions) and [Russian](https://github.com/vit9696/AppleALC/wiki/Часто-задаваемые-вопросы).
