### ISSUE TITLE
10.12 compatability 

### ISSUE THREAD

**Issue by Gamedev1909** [vit9696/AppleALC#54]
[AppleHDA.kext.zip](https://github.com/vit9696/AppleALC/files/313188/AppleHDA.kext.zip)
Here ya go work your magic for 10.12

**Comment by vit9696** [comment]
Yawn, proper hackintoshers do sleep in this hour) Why do yout think AppleALC should stop working in 10.12? And even if so, your AppleHDA kext is practically useless. Give me the DEBUG boot log with -alcdbg in boot-args.

**Comment by vit9696** [comment]
AppleALC works just fine in /S/L/E in 10.12 according to the tests.
https://applelife.ru/threads/applealc-dinamicheskij-patching-applehda.1171672/page-157#post-596015
Since kext injection is half broken in Clover at the moment I may imagine issues when loading from EFI partition but even that is unlikely. Any further report without providing debug logs will be ignored.

**Comment by Gamedev1909** [comment]
Bad dev is bad
