### ISSUE TITLE
ALC1150 - Simultaneous speakers and headphones

### ISSUE THREAD

**Issue by hameerabbasi** [vit9696/AppleALC#77]
Hello. I'm using the ALC1150. The issue I'm having is that after sleep, [Codec Commander](https://github.com/RehabMan/EAPD-Codec-Commander) restarts all the audio devices so they work.

The issue, however is that it only restarts one of the headphones (front panel) and 2-channel speakers (back panel), so if I switch from one to the other it doesn't work after sleep.

Is there a layout ID that allows both to exist separately? It would be useful for me in other scenarios as well.

**Comment by vit9696** [comment]
Hello,
If I understood you correctly you need a layout with headphones/speakers switch autodetect. Unfortunately we do not have any, and there are no plans to add one. 
From what I know Codec Commander should be able to restart both if properly configured, and that should be the right way to do it. However, I cannot properly tell you the configuration options you need, since I have never used Codec Commander myself.

**Comment by hameerabbasi** [comment]
The thing is, the autodetect/switch already happens, the headphones change into internal speakers when I remove them from the front panel (using layout ID 11).

I want a way to stop it, so that all the devices should be listed at the same time.

**Comment by vit9696** [comment]
Oh, sorry. I wrote 'with' when I meant to write 'without'. All the current layouts have autodetect enabled, and you need to add a custom one to disable it.
